blank_issues_enabled: true
contact_links:
  - name: "Get support or report unexpected behavior"
    about: "For questions, issues, or anything that seems off—start here on the forum"
    url: "https://forum.getodk.org/c/support/6"
  - name: "Request a feature"
    about: "For when ODK Web Forms is missing functionality"
    url: "https://forum.getodk.org/c/features/9"
